const { faker } = require('@faker-js/faker');
// perdor librarin faker per te shenuar te dhena random, por qe kane sens dhe i kalojn validimet
describe('Login and Registration Test', () => {
  let username;
  let password;
  beforeEach(() => {
    // Replace 'http://example.com' with the URL where your login form is hosted
    cy.visit('https://parabank.parasoft.com/parabank/index.htm');
    username = faker.internet.userName();
    password = faker.internet.password();
  });

  it('should type the username and password with invalid data', () => {
    // Confirm the error does not exist because we have not failed yet
    cy.get('#rightPanel').should('not.contain', 'An internal error has occurred and has been logged.');

    // Type 'aa' in the username input field
    cy.get('input[name="username"]').type('aa1');
    // Assertions to check if the username input was successful
    cy.get('input[name="username"]').should('have.value', 'aa1');

    // Type '123456' in the password input field
    cy.get('input[name="password"]').type('123456');
    // Assertions to check if the password input was successful
    cy.get('input[name="password"]').should('have.value', '123456');

    // Click on the login button
    cy.get('input[type="submit"][value="Log In"]').click();

    // Check if error message is displayed for incorrect username or password
    cy.get('#rightPanel').should('contain', 'An internal error has occurred and has been logged.');
});



//   it('should be able to register', () => {
//     // click on tag <a> that is register.htm or with value name
//     // cy.get('a[href="/parabank/logout.htm"]')
//     cy.get('#customer\\.firstName').type('aa');
//     cy.get('#customer\\.lastName').type('aa');
//     // continue filling out other informations as well. Feel free to user faker.internet.* to fillout firstName, lastName, or zip code for example
//     cy.get('#customer\\.username').type(username);
//     // type username variable which is dynamically generated by faker
//     // click register / same as we click in Log in
//     // logout, so we can login with the credentials provided in registration
//     cy.get('input[name="username"]')
//       .type(username);
//     // write password same as we have written username
//     // click login
//     // verify you logged in successfully (eg. welcoming message per {username})
//   });
});