const { faker } = require('@faker-js/faker');
// perdor librarin faker per te shenuar te dhena random, por qe kane sens dhe i kalojn validimet
describe('Login and Registration Test', () => {
  let username;
  let password;
  beforeEach(() => {
    // Replace 'http://example.com' with the URL where your login form is hosted
    cy.visit('https://parabank.parasoft.com/parabank/index.htm');
    username = faker.internet.userName();
    password = faker.internet.password();
  });

  it('should type the username and password with invalid data', () => {
    // confirm the error is not existing because we did not fail yet
    cy.get('p.error').should('not.exist');
    // type testuser in username
    cy.get('input[name="username"]')
      .type('testuser');
    // Assertions to check if the input was successful
    cy.get('input[name="username"]').should('have.value', 'testuser');
    // type testuser in password
    // use the same idea as username
    // Assertions to check if the password input was successful
    // click on login button
    cy.get('input[type="submit"][value="Log In"]').click();
    // confirm now the error is visible and validation failed
    // click on register now

  });
  it('should be able to register', () => {
    // click on tag <a> that is register.htm or with value name
    // cy.get('a[href="/parabank/logout.htm"]')
    cy.get('#customer\\.firstName').type('John');
    cy.get('#customer\\.lastName').type('Doe');
    // continue filling out other informations as well. Feel free to user faker.internet.* to fillout firstName, lastName, or zip code for example
    cy.get('#customer\\.username').type(username);
    // type username variable which is dynamically generated by faker
    // click register / same as we click in Log in
    // logout, so we can login with the credentials provided in registration
    cy.get('input[name="username"]')
      .type(username);
    // write password same as we have written username
    // click login
    // verify you logged in successfully (eg. welcoming message per {username})
  });
});